version: '3.4'

services:
  php:
    user: ${CURRENT_UID}
    container_name: "php-fpm"
    build:
      context: infra/php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ${APP_FOLDER}:/var/www:rw,cached
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql:
    container_name: "mysql"
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - '3306'

  nginx:
    container_name: "nginx"
    build:
      context: infra/nginx
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    ports:
      - "8000:80"

volumes:
  mysql-data: